from fpdf import FPDF
import os
from datetime import datetime

class ComplianceReport(FPDF):
    def header(self):
        # Logo placeholder (if exists) or Text Header
        self.set_font('Arial', 'B', 16)
        self.cell(0, 10, 'CSIDC Land Sentinel', 0, 1, 'C')
        self.set_font('Arial', 'I', 10)
        self.cell(0, 10, 'Official Compliance Audit Report', 0, 1, 'C')
        self.line(10, 30, 200, 30)
        self.ln(10)

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.cell(0, 10, f'Page {self.page_no()}/{{nb}} | Generated by CSIDC AI Sentinel on {datetime.now().strftime("%Y-%m-%d")}', 0, 0, 'C')

def generate_pdf_report(project_data, output_path):
    """
    Generate a professional PDF report for a project.
    """
    pdf = ComplianceReport()
    pdf.alias_nb_pages()
    pdf.add_page()
    
    # 1. Project Info
    pdf.set_font('Arial', 'B', 12)
    pdf.cell(0, 10, f"Project ID: {project_data.get('id', 'N/A')}", 0, 1)
    
    pdf.set_font('Arial', '', 10)
    pdf.cell(95, 8, f"Plot Name: {project_data.get('name', 'N/A')}", 0, 0)
    pdf.cell(95, 8, f"Area ID: {project_data.get('plot_id', 'N/A')}", 0, 1)
    pdf.cell(95, 8, f"Date Scanned: {project_data.get('created_at', str(datetime.now())).split('T')[0]}", 0, 1)
    
    pdf.ln(5)
    
    # 2. Compliance Status Badge
    results = project_data.get('results', {})
    metrics = results.get('change_detection', {})
    status = metrics.get('status', 'UNKNOWN')
    compliance_score = results.get('compliance_score', 0)
    
    pdf.set_font('Arial', 'B', 14)
    if status == 'COMPLIANT':
        pdf.set_text_color(22, 163, 74) # Green
        pdf.cell(0, 10, f"STATUS: COMPLIANT (Score: {compliance_score}/100)", 0, 1, 'L')
    elif 'VIOLATION' in status or 'ENCROACHMENT' in status:
        pdf.set_text_color(220, 38, 38) # Red
        pdf.cell(0, 10, f"STATUS: VIOLATION DETECTED (Score: {compliance_score}/100)", 0, 1, 'L')
    else:
        pdf.set_text_color(100, 100, 100)
        pdf.cell(0, 10, f"STATUS: {status}", 0, 1, 'L')
        
    pdf.set_text_color(0, 0, 0) # Reset
    pdf.ln(5)
    
    # 3. Images (Before/After)
    # Check visuals
    base_dir = os.getcwd()
    # Path construction might need adjustment depending on how paths are stored (absolute vs relative)
    # results['outputs']['heatmap'] is usually something like "/results/xyz.png"
    # We need absolute path for FPDF
    
    # Heuristic to find images
    project_dir = os.path.join(base_dir, "uploads", project_data['id'])
    
    # Add Title for images
    pdf.set_font('Arial', 'B', 10)
    pdf.cell(95, 8, "Reference Layout", 0, 0, 'C')
    pdf.cell(95, 8, "Satellite Analysis", 0, 1, 'C')
    
    y_start = pdf.get_y()
    
    # Try to load images
    ref_img = os.path.join(project_dir, "reference.png")
    sat_img = None
    
    # For satellite result, use the generated heatmap if available
    # The path in JSON is relative "/results/..."
    output_key = results.get('outputs', {}).get('heatmap')
    if output_key:
        # Remove leading slash if present
        if output_key.startswith("/") or output_key.startswith("\\"):
            output_key = output_key[1:]
        sat_img = os.path.join(base_dir, output_key)
    
    # Display Images
    try:
        if os.path.exists(ref_img):
            pdf.image(ref_img, x=10, y=y_start, w=90)
        else:
            pdf.text(30, y_start + 30, "[Reference Missing]")
            
        if sat_img and os.path.exists(sat_img):
            pdf.image(sat_img, x=110, y=y_start, w=90)
        else:
            pdf.text(140, y_start + 30, "[Analysis Missing]")
            
    except Exception as e:
        print(f"Error adding images to PDF: {e}")
        
    pdf.ln(80) # Space for images
    
    # 4. Detailed Metrics Table
    pdf.set_font('Arial', 'B', 12)
    pdf.cell(0, 10, "Detailed Metrics", 0, 1)
    
    pdf.set_font('Arial', '', 10)
    pdf.set_fill_color(240, 240, 240)
    
    # Row 1
    pdf.cell(100, 8, "Total Valid Area (sqm)", 1, 0, 'L', 1)
    pdf.cell(90, 8, f"{project_data.get('approved_area_sqm', 'N/A')}", 1, 1, 'R')
    
    # Row 2
    pdf.cell(100, 8, "Encroached Area (sqm)", 1, 0, 'L', 1)
    # Convert pixels to sqm estimation if not present (mock conversion)
    encroached_px = metrics.get('changed_pixels', 0)
    # Assuming 1 px ~ 0.1 sqm for demo if not calibrated
    estimated_sqm = round(encroached_px * 0.1, 2) 
    pdf.cell(90, 8, f"{estimated_sqm} (Est.)", 1, 1, 'R')
       
    # Row 3
    pdf.cell(100, 8, "Deviation Percentage", 1, 0, 'L', 1)
    pdf.cell(90, 8, f"{metrics.get('change_percentage', 0)}%", 1, 1, 'R')
    
    pdf.ln(10)
    
    # 5. Recommendation
    pdf.set_font('Arial', 'B', 12)
    pdf.cell(0, 10, "AI Recommendations", 0, 1)
    
    pdf.set_font('Arial', '', 10)
    actions = results.get('audit_report', {}).get('compliance', {}).get('recommended_actions', [])
    if actions:
        for action in actions:
            pdf.cell(10, 8, "-", 0, 0)
            pdf.cell(0, 8, action, 0, 1)
    else:
        pdf.cell(0, 8, "No specific actions recommended.", 0, 1)
        
    # Valid Signature Layout
    pdf.ln(20)
    pdf.line(130, pdf.get_y(), 190, pdf.get_y())
    pdf.text(140, pdf.get_y() + 5, "Authorized Signatory")
    pdf.text(145, pdf.get_y() + 10, "CSIDC Nodal Officer")
    
    pdf.output(output_path)
    return output_path
